flags: {}
extra-package-dbs: []
packages:
 
extra-deps: []
resolver: lts-13-18
deps:   Cabal-1.18.1.7
        haskell-src-exts-1.15.0.1
        hlint-1.8.61
        monad-control-0.3.3.1
        monad-journal-0.2.4
        mtl-2.0.1.1
        syb-0.4.4
        text-1.1.1.4

allow-newer: true
